### ISSUE TITLE
Type checking for serialization

### ISSUE THREAD

**Issue by Yuzhen11** [husky-team/husky#102]
If user writes something (Obj, Msg) to be serialized without providing the serialization overload functions, the default one will be used. The default serialization function just simply serialize the memory of the struct. Undefined behavior will incur if the user-defined type uses memory outside of the struct. 

More friendly detection or warning is needed. 

The first step is that if lacking serialization functions, an error will be reported. 

The ultimate goal is that we try to do the serialization as much as possible. If the struct really cannot be serialized, we report an error (most likely in compile time).

**Comment by Yuzhen11** [comment]
Using `std::is_trivially_copyable`, we can let the default serialization functions to only accept types that are trivially copyable. It means that the storage is contiguous and the default copy ctor is used. http://www.cplusplus.com/reference/type_traits/is_trivially_copyable/

An error will be reported is the use types that are not trivially copyable and fail to provide serialization functions.

However, what still need to do is to help user as much as possible in for example this case:
```c++
struct A {
  int a;
  std::vector<int> b;
};
```
Need to figure out way to help users serialize struct like this automatically.

**Comment by Kelvin-Ng** [comment]
Unfortunately this is not so useful because
```C++
struct A {
    int* a;
};

cout << std::is_trivially_copyable<A>::value << endl;
```
shows 'true'.

**Comment by Yuzhen11** [comment]
Yes, you are right!

But we can expect that user would better not to write struct like this:

1. Avoid using raw pointer if possible after C++11, one can turn to unique_ptr or shared_ptr instead.
2. If raw pointer is used, a deep copy constructor is expected.

Now, we just bear in mind that it's not a good practice to write struct like this. And see whether we have solutions to detect this situation.
