### ISSUE TITLE
A Convenient Representation of Data for Machine Learning in General

### ISSUE THREAD

**Issue by Kelvin-Ng** [husky-team/husky#106]
It is needed because it reality, the machine learning algorithms will be used together. For example, the output of an algorithm will become the input of another algorithm. Currently people are just adding arithmetics operator overloads for `std::vector`. There are at least two drawbacks.
1. It 'hijacks' the general-purpose STL container. When the users want to overload `std::vector` operators for other purposes (within his own application), things will go wrong.
2. Dense and sparse vectors are not taken care in a unified way.

A better idea is to create our own class so that the above two problems can be solved. The first problem is solved trivially. The second problem can be solved by providing high-level APIs to encapsulate the underlying implementation of the vectors. API of sparse vector should be the subset of dense vector. The functions accpeting vectors as inputs can then specify whether only dense vector can be used or both, so as to provide much flexibility.

An example written by me can be found at https://github.com/Kelvin-Ng/VR-SGD-Implementation . The class `Vector` can be found at lib/Vector.{h,t}pp. You can also read other files to see examples of how to use it. I have tried my best to make it as general as possible, yet reducing performance overhead to the best of my ability.

If you think that it is good, I will make a pull request here, but before that, I would like some comments about function / variable naming, etc.

**Comment by lijinf2** [comment]
The idea is good! For user-friendliness, there should be some higher level abstractions. BTW, there are also some pioneering works on Spark that may help. Machine learning on Apache Flink also adopts similar designs. You might take a look and see whether it is what you need. 

http://spark.apache.org/docs/latest/mllib-data-types.html
