### ISSUE TITLE
[Lib][ML] Replace `std::vector` with `husky::lib::Vector`

### ISSUE THREAD

**Issue by zzxx-husky** [husky-team/husky#115]
As we now have our own classes to represent vectors and data points in PR #108 and it's better not to hijack `std::vector`, we should update current implementation of Linear Regression, Logistic Regression and SVM and change to use our own classes.

**Comment by TatianaJin** [comment]
@zzxx-husky

**Comment by kygx-legend** [comment]
BTW, I think the wiki about the ml part should be included later. Help others use ml libraries.
