### ISSUE TITLE
Naming and other miscellaneous things about husky::lib::{Vector,DataPoint}

### ISSUE THREAD

**Issue by Kelvin-Ng** [husky-team/husky#117]
1. The name of DataPoint looks a bit confusing. Should it be renamed to something like LabeledPoint?

2. Should DataPoint be more general that x is not necessarily a vector?

3. Should DataPoint include id field so that it can be an husky object directly, or be subclassed?

**Comment by kygx-legend** [comment]
Are these some suggestions for PR #116?

**Comment by Kelvin-Ng** [comment]
Related but not limited to that PR.

**Comment by zzxx-husky** [comment]
For 1, seems better to change the name because many things can be called DataPoint.
For 3, I think whenever we need a data point object class, we can subclass `DataPoint` and add `KeyT` definition in the subclass. Seems not necessary to make `DataPoint` itself a husky object class.

**Comment by Kelvin-Ng** [comment]
For 1, I think so.
For 2, I think so as well. In addition, I think there should be some naming convention for the subclasses.

**Comment by TatianaJin** [comment]
For 1, what data do you want DataPoint to represent? Records with features and labels?
For 2, are you considering the performance using vector or the ability of DataPoint to represent data? 
    For performance, considering different containers, I think vector is most suitable.
    For representation, if you are considering things like kernel representations which involve matrices, I think another class may be used since in that case you will have one instance to represent a whole set of data instead of a single record.
For 3, I agree.

**Comment by Kelvin-Ng** [comment]
@TatianaJin 
For 1, yes, records with features and labels.
For 2, my concern is on representation. I have not thought of any example of machine learning that the features are in matrix form, but it would be good to be more general. Kernel is not related to data representation so it is not related.

**Comment by Kelvin-Ng** [comment]
Sometimes data may be in matrix form like images, but such kind of data can be simply flattened to vector form. I don't know if there is a possibility that the features cannot be flattened.

**Comment by Kelvin-Ng** [comment]
For LabeledPoint, actually even the label is not necessarily a scalar...

**Comment by Kelvin-Ng** [comment]
We settle at pull request #125. Closed.
