### ISSUE TITLE
Read/Write object list(after serialization) to disk

### ISSUE THREAD

**Issue by kygx-legend** [husky-team/husky#133]

**Comment by ddmbr** [comment]
How about we draft the APIs first? For example, we may make a base class "DiskStore", which support the `retrieve()` and `store()` pure virtual method (better names?). Anything subclassing it should implement these methods, but we may start from ObjList first.

**Comment by kygx-legend** [comment]
It's a good idea. Maybe I will give an example in IDL.
BTW, I have finished the part of ObjList-to-BinStream. Do you think it's better to use `mmap` or read/write to disk directly? I think the former is better.

**Comment by ddmbr** [comment]
We should allow users to completely destroy an ObjList and then recover it from disk. @MiaoLoud will handle it.

**Comment by kygx-legend** [comment]
I think it's done now.
