### ISSUE TITLE
Segmentation fault when running PI example

### ISSUE THREAD

**Issue by lmatz** [husky-team/husky#137]
Hi guys, I find a weird behavior when running PI example in different configurations.
The commit I use is 0566619 [Husky] Use HuskyException instead (#118)].
When I run in the configuration
<img width="225" alt="config-5thread1worker" src="https://cloud.githubusercontent.com/assets/5791930/20353920/6405909c-ac57-11e6-9b97-32b50bf3741d.png">
it works fine.

But then I change it to 
<img width="222" alt="config-5thread2worker" src="https://cloud.githubusercontent.com/assets/5791930/20353945/7b627e94-ac57-11e6-9bd2-d124310db529.png">
Then error happens:
<img width="832" alt="err2" src="https://cloud.githubusercontent.com/assets/5791930/20353963/8efee4c4-ac57-11e6-89f0-f2b281f2e62f.png">

So I thought maybe it causes problem when there are multiple machines, but it turns out not.
Since when I run in this configuration:
<img width="229" alt="config-3thread3worker" src="https://cloud.githubusercontent.com/assets/5791930/20354104/0b7a64e2-ac58-11e6-825e-44ac75e9547a.png">
it succeeds:
<img width="650" alt="success-3thread3worker" src="https://cloud.githubusercontent.com/assets/5791930/20354142/29b3a55e-ac58-11e6-9b76-62ad86733e24.png">

But....
when:
<img width="217" alt="config-4thread4worker" src="https://cloud.githubusercontent.com/assets/5791930/20354524/6ca9216c-ac59-11e6-99ad-b4b418d61821.png">

<img width="833" alt="err-4thread4worker" src="https://cloud.githubusercontent.com/assets/5791930/20354552/82abfe76-ac59-11e6-828a-ae91d9d12ac0.png">

These behavior does not happen when I run the PI example using commit 227038e [Travis] Appoint to build release version (#83). The configurations above all succeed when I git reset to that version. So it may be caused by some recent commits.

**Comment by ddmbr** [comment]
Thanks for your findings! I'll look into it.
