### ISSUE TITLE
Change ChannelFactory and ObjListFactory to ChannelStore and ObjListStore

### ISSUE THREAD

**Issue by Yuzhen11** [husky-team/husky#140]
As the definition of factory, it should only create things but not store things. Since in our ChannelFactory and ObjListFactory, they also store things. We'd better give them new names.

Now, the best names we can come up with are ChannelStore and ObjListStore. Please propose if you have better names. 

Another issue:

Prevent users from creating the channel or objlist directly.

**Comment by kygx-legend** [comment]
Can we let `factory` to create and `manager` to store/manage instead of that `factory` does both currently?

**Comment by Yuzhen11** [comment]
Yes, we can. But it'd better to keep things simple.

**Comment by kygx-legend** [comment]
I found the information about this change in wiki is not updated. @Yuzhen11

**Comment by Yuzhen11** [comment]
Oh, I will update it now.
