### ISSUE TITLE
Example is showing no output; how to use Scala/Python

### ISSUE THREAD

**Issue by TomNash** [husky-team/husky#142]
I'm trying to run the simple PI example after compiling/building following the steps in the README. I'm just running on a single node right now as I try to understand and get everything working, but there's no output. I saw a different issue #137 showed output where digits of pi were printed to the console. Is there another option to use, is the `config.ini` set properly?

![screenshot from 2016-11-17 14 26 43](https://cloud.githubusercontent.com/assets/8193065/20404285/55cb1fe4-acd2-11e6-9b8d-01ca57674bc9.png)

I saw on the website there is a Python or Scala API, how would I go about installing one of those?

**Comment by ddmbr** [comment]
That's strange. This can happen if the workers you give do not match any hostname. But I saw that your hostname is `tom-husky` and it matches. Can you check the exit code (e.g., `echo $?`), and see whether the program terminates with an error?

PyHusky/ScHusky are on bitbucket repos and currently only accessible to a small group of people working with them. we are moving them out to Github soon and I expect that PyHusky will be released first.

**Comment by kygx-legend** [comment]
The `config.ini` looks normal. Did you run it on the latest version of Husky?

**Comment by TomNash** [comment]
Thanks for the followups.

Using the most recent version, yes.
Exit code is 0.

I added print statement in the `pi()` function of `pi.cpp` and recompiled to see where the problem was occurring, but it never gets printed. Putting it in `main()` it's displayed, though.

Could this be the issue?

Ran the `HuskyUnitTest` and it fails on `TestSessionLocal.ThreadFinalizer`
![screenshot from 2016-11-18 11 08 42](https://cloud.githubusercontent.com/assets/8193065/20436771/626a1194-ad7f-11e6-843f-dad9bde3b12d.png)

**Comment by zzxx-husky** [comment]
Hi @TomNash , thanks for your finding. I just put a PR to fix this unittest failure. But I don't think this is the reason for the PI program showing no output.

Would you please try to change the value of `master_host` to `127.0.0.1` and `info` in `[worker]` section to `127.0.0.1:3`?

And would you please tell me some information about your operating system (it looks like ubuntu) and compiler? This may help us test Husky well.

**Comment by TomNash** [comment]
Changing to seems to `127.0.0.1` seems to have solved it.

![image](https://cloud.githubusercontent.com/assets/8193065/20442900/90bcb0c4-ad98-11e6-8724-e2d609fb1799.png)

**Comment by ddmbr** [comment]
I guess your VM didn't resolve the hostname `tom-husky` due to some reason. You may try `ping tom-husky` to verify it. Are you running on 32-bit Ubuntu VM (Virtualbox or VMWare)? I want to reproduce this issue on my side.
