### ISSUE TITLE
Implement K-means

### ISSUE THREAD

**Issue by lijinf2** [husky-team/husky#145]
K-means algorithm is essential for many machine learning algorithms such as Spectral clustering, Learning to Hash and so on. There was an old implementation in the bitbucket repository and I think someone can move it to the github repository. BTW, it will be better to also implement the K-means++ and K-means| | algorithms.

**Comment by kygx-legend** [comment]
So who is the suitable one to do that?

**Comment by lijinf2** [comment]
I and Yat Long are discussing this issue.

**Comment by ddmbr** [comment]
How's the status of this one?

**Comment by lijinf2** [comment]
@ylchan87  will takes this, but he is preparing the final. After that, he will start to work on it.

**Comment by ylchan87** [comment]
Will work on it after exam and present. Sorry for that..

**Comment by ylchan87** [comment]
I have just written Kmeans in my fork:
https://github.com/ylchan87/husky/commit/2eac83414b43774b060f696e158b2b41626e8871

2 issues:
a) It is another small standalone prog, while #186 is proposing a unifying framework for ML algos
b) Just basic Kmeans, not yet Kmeans++

**Comment by ylchan87** [comment]
Implemented Kmeans++ in
https://github.com/ylchan87/husky/commit/00afaf315f66e485557f3f0b51c054d7fb19d64b

**Comment by lijinf2** [comment]
@ylchan87 Hi Yat long, can you make a pull request if you have finish the implementation. The KMeans and KMeans++ can be put in two separate pull requests.
