### ISSUE TITLE
Headers of third-party components missing

### ISSUE THREAD

**Issue by ddmbr** [husky-team/husky#160]
A recent commit requires `glog/logging.h` to be available in search path, however the existing CMake script will install it in build directory and this is self-contradicting.

I think a better fix is that we put all third-party components into a directory `$HUSKY_ROOT/thirdparty/`. In this case, no matter what mode we are using (Release, Debug, etc.), we use the same copy of them. And plus, we can include the headers from that directory, meaning that we may do `#include "thirdparty/glog/logging.h".

**Comment by kygx-legend** [comment]
Yes, and I want to put other third party such as zmq\hdfs\tcmalloc in that directory.
The rule is:
1. Find the libraries in system path; If no, switch to step 2;
2. Download the libraries in `thirdparty` and set the path.

**Comment by ddmbr** [comment]
I think you may try to solve zmq and google components first. Since hdfs stuff is more difficult to build, I'll help you to solve it later.

**Comment by kygx-legend** [comment]
Fine.

**Comment by ddmbr** [comment]
@lijinf2 is having the same problem

**Comment by kygx-legend** [comment]
I know. Please modify the CMakeList.txt in each directory with `include_directories(${PROJECT_SOURCE_DIR} ${EXTERNAL_INCLUDE})`. I have put all external includes in `${EXTERNAL_INCLUDE}`. @lijinf2
