### ISSUE TITLE
Support for Unlabeled data

### ISSUE THREAD

**Issue by rylanchiu** [husky-team/husky#180]
Seems that Husky now just support `LabeledPoint ` data, that is, a label is assumed to be a must in the dataset. Given some dataset for unsupervised learning can have no label, will husky consider supporting Unlabeled data? Thanks.

**Comment by ddmbr** [comment]
@Kelvin-Ng Any idea on this issue?

**Comment by Kelvin-Ng** [comment]
A bare `Vector` will do.

**Comment by rylanchiu** [comment]
@Kelvin-Ng  But if I use a simple Vector, can I still use `load_data`, seems that it assumes a `LabeledPoint ` as parameter.

**Comment by Kelvin-Ng** [comment]
No you can't, but that is reasonable because `load_data` is designed to load the data in LIBSVM or TSV format. I am not sure about TSV, but LIBSVM format contains label.

May I know what data format are you going to load?

**Comment by rylanchiu** [comment]
@Kelvin-Ng For convenience, now I use a dataset in libsvm so that I can use `load_data` appropriately. I didn't know there is such limit in `load_data`. I wonder what if the dataset is text? How can I load the data with husky?

**Comment by Kelvin-Ng** [comment]
I think all datasets in LIBSVM contains label?

For any custom data format, you can simply write your own function to load the data. You can take a look at the code of `load_data` to see how to write it.

If you use a LIBSVM format with labels but you want to just ignore the labels, you can copy the `load_data` function and make some small modifications to it.

**Comment by ddmbr** [comment]
For examples of general-purpose data loaders, you may want to look at `examples/wc_mr.cpp`(HDFS/NFS) or `examples/tfidf.cpp`(MongoDB).

**Comment by rylanchiu** [comment]
Yes, the dataset I use contains labels now, since I want to use `load_data` directly. But another question for libsvm is whether it supports multi labels?

**Comment by rylanchiu** [comment]
And now I got the idea of loading data in customized way. Thanks for both of you.

**Comment by Kelvin-Ng** [comment]
By definition LIBSVM format supports only one label with a number of features, but you can definitely create your own format (to support no label or multiple labels) and write your own `load_data` function for that.
