### ISSUE TITLE
About the iterators of Vector

### ISSUE THREAD

**Issue by Kelvin-Ng** [husky-team/husky#190]
Currently there are 6 types of iterators for each Vector class (i.e. 6 for dense and 6 for sparse), namely:

1. `Iterator`
2. `ConstIterator`
3. `ValueIterator`
4. `ConstValueIterator`
5. `FeaValIterator`
6. `ConstFeaValIterator`

Currently, for sparse vector, `Iterator` is just an alias of `FeaValIterator`. For dense vector, `Iterator` is just an alias of `ValueIterator`. For both dense and sparse vector, `begin()` returns their own `Iterator` respectively. I intended to make sparse vector have the subset (or equal) of interface of dense vector, but currently `begin()` becomes an outlier. It doesn't look good. To fix the problem, I have three recommendation but I don't know which to choose:

1. `begin()` of both dense vector and sparse vector return `ValueIterator`
2. `begin()` of both dense vector and sparse vector return `FeaValIterator`
3. Cancel `begin()` method. Only leave `begin_value()` and `begin_feaval()`

Cancelling `begin()` has a small drawback that users can no longer use `for (auto&& entry : vec)` to access the elements in the `Vector`.

**Comment by ddmbr** [comment]
Is this issue still valid?

**Comment by Kelvin-Ng** [comment]
It is not needed as we will switch to Eigen.
