### ISSUE TITLE
How to pass the variable to lambda function of `update_any`

### ISSUE THREAD

**Issue by rylanchiu** [husky-team/husky#195]
Here is my code:

    int num_features = husky::lib::ml::load_data(husky::Context::get_param("train"), train, husky::lib::ml::kLIBSVMFormat);
    using LabeledPointHObj = husky::lib::ml::LabeledPointHObj<double, double, true>;
    auto& ac = husky::lib::AggregatorFactory::get_channel();
    vector<DenseVector<double>> XT_init(num_features, (N, 0));
    Aggregator<vector<DenseVector<double>>> XT(XT_init);
    husky::list_execute(train, {}, {&ac}, [&XT](LabeledPointHObj &data){
  	XT.update_any([&](vector<DenseVector<double>>& x){
  		for (int k=0; k<num_features; ++k){
  			x[k][data.key] = data.x[k];
  		}
  	     });
      });

And I got this error: `error: 'num_features' is not captured`. So how should I pass the variable `num_features` for `update_any`? In the example in wiki, seems that the variable outside `update_any` can be used directly. Why does the error occur here and how should I deal with it? Thanks!

**Comment by zzxx-husky** [comment]
The code looks fine.

As long as (1) **num_features** can be seen at the place where **update_any** is used, and (2) you put a **&** in the capture list of the lambda, the lambda can capture **num_features**.

Did you save the file before you compile it?

**Comment by zzxx-husky** [comment]
It looks like the execute function used in list_execute doesn't capture num_features. Thus you cannot use num_features in the execute function. 

Try to change **[&XT]** to **[&XT, &num_features]**?

**Comment by rylanchiu** [comment]
@zzxx-husky Thanks for reply and  yes. I think I have done both (1) and (2). But indeed I also have another `list_execute` before this one:

     Aggregator<int> N(0);
     husky::list_execute(train, {}, {&ac}, [&N](LabeledPointHObj &data){
  	     N.update(1);
     });

Does it matter? Thanks.

**Comment by rylanchiu** [comment]
@zzxx-husky  Thanks for reply! It solves my problem! Maybe the example in wiki should be edited?

**Comment by zzxx-husky** [comment]
@rylanchiu Just see your reply. Sure I will update wiki but I don't quite understand which part of the wiki has problems. Would you please tell me that?

**Comment by rylanchiu** [comment]
@zzxx-husky  Indeed it has no error. I just think it would be better if this kind of example could be included in the `Aggregator` section. 

May I ask another two questions?
The first one is can I use the `key` value of `LabeledPointHObj` as an index of the data to construct a matrix `X`(`num_features`*`num_data`) ?
The second one is why does the code above have another error:

       error: no match for 'operator[]' (operand types are 'husky::lib::Vector<double, true>' and 'int')
         mat[k][data.key] = data.x[k];

As far as I know, the `x` in `LabeledPointHObj` should be a `Vector` and I can use `vec[idx]` to get the value in `idx`. Please correct me if I was wrong. Thanks a lot!

**Comment by rylanchiu** [comment]
Or I need to create a new issue? @zzxx-husky
