### ISSUE TITLE
Bug in building release with debug info ( -O2 -g)

### ISSUE THREAD

**Issue by kygx-legend** [husky-team/husky#206]
How to reproduce(100% reproduced):

1. Change to use `-O2 -g` to build HuskyUnitTest.
2. Run `./HuskyUnitTest --gtest_filter=TestMailbox.Iterative`.
2. The error is:
```
[ RUN      ] TestMailbox.Iterative
Please poll before recv
Segmentation fault
```

**Comment by lmatz** [comment]
Use the current commit
<img width="379" alt="current commit" src="https://cloud.githubusercontent.com/assets/5791930/23214432/a450196c-f949-11e6-9f59-9e0fe9911eea.png">

<img width="679" alt="cmake file" src="https://cloud.githubusercontent.com/assets/5791930/23214425/9fade254-f949-11e6-87ce-31986dfb21a7.png">

<img width="416" alt="cmake command" src="https://cloud.githubusercontent.com/assets/5791930/23214451/bb5e8efe-f949-11e6-89b4-07e7f187120d.png">

<img width="276" alt="make command" src="https://cloud.githubusercontent.com/assets/5791930/23214460/c10be554-f949-11e6-9a0e-5080d34d3475.png">

<img width="1240" alt="make output" src="https://cloud.githubusercontent.com/assets/5791930/23214469/c37e4a70-f949-11e6-8ea8-561fa72299be.png">

<img width="793" alt="test output" src="https://cloud.githubusercontent.com/assets/5791930/23214473/c63e260e-f949-11e6-9e50-448cd077a5fd.png">
do I miss something?

**Comment by kygx-legend** [comment]
Seems it has been fixed by something. Can you help run the whole HuskyUnitTest many times and try some applications like wc in distributed env?

**Comment by lmatz** [comment]
Sure. In which commit does the test error pop? I may check how it is fixed.

**Comment by kygx-legend** [comment]
I think you can check the commits around `Jan 6`. But the checking manually is heavy. To implement a simple bisect checker is a good solution. :)

**Comment by lmatz** [comment]
No error occurs during the mailbox test or full test in those commits modifying mailbox or its dependent files in Dec and before Jan 6. Each commit runs test ten times.

**Comment by kygx-legend** [comment]
Your first comment reminds me that you run the test on proj10. What if running on proj99/master? This bug was found on proj99.

**Comment by lmatz** [comment]
you mean ssh to proj99? I don't have access yet.

**Comment by kygx-legend** [comment]
Yes, could you give me the account name you want to use? I'll set up for you.

**Comment by lmatz** [comment]
just 'liuzhi' is fine, thanks

**Comment by kygx-legend** [comment]
I have created your account on master. The password is the same as use name. And please don't store any files in your home dir, go to /data/liuzhi instead. Only master set up but not other workers, if you want to use them later, please let me know.

**Comment by lmatz** [comment]
What may lead to the difference between running on proj10 and proj99? They had the same version of gcc.

**Comment by kygx-legend** [comment]
The hardware of proj99 is older than proj10, which means it will be run a little bit slower. Proj99 is the oldest machine in our cluster.

**Comment by lmatz** [comment]
Still no errors pop up. But they do have different versions of glibc. Have no idea...

**Comment by kygx-legend** [comment]
Thanks for helping reproduce. I'll check and submit a patch to enable this option.
