### ISSUE TITLE
Inheriting Serialization and Deserialization Functions

### ISSUE THREAD

**Issue by Kelvin-Ng** [husky-team/husky#210]
Currently, we use `operator<<` and `operator>>` to do serialization and deserialization respectively. Since they are not the member functions of the corresponding classes, they are not inherited. So, each subclass of them must have another serialization and deserialization functions. This is undesired because the authors of the subclasses will need to access the members of the parents.

One may make functions called `serialize()` and `deserialize()`, and call them in `operator<<` and `operator>>` respectively, but this is troublesome.

The most general versions of `operator<<` and `operator>>` should be able to do that automatically.

**Comment by zzxx-husky** [comment]
I think the subclass can use the operator << and >> defined for the base class without problems, if the subclass doesn't need to serialize or deserialize any more things. The following code works fine.
```c++
#include <iostream>

struct A {
	int a;
};

struct B: public A {
	int b;
};

std::ostream& operator<<(std::ostream& os, A& a) {
	os << "a=" << a.a;
	return os;
}

/* // In case the sub class wants to serialize its own members
std::ostream& operator<<(std::ostream& os, B& b) {
	os << static_cast<A&>(b) << " b=" << b.b;
	return os;
}*/

int main() {
	B b;
	b.a = 1;
	b.b = 2;
	std::cout<<b<<std::endl;
}
```

Is this what you are talking about?

**Comment by Yuzhen11** [comment]
Yes, but once you have a general template function like this:
```c++
template<typename T>
BinStream& operator<<(BinStream& stream, const T& x);
```
It will match the general one instead of the one take the base class reference as parameter.
