### ISSUE TITLE
Definitions (like -DWITH_HDFS) could not be visible for top project

### ISSUE THREAD

**Issue by Gyingguo** [husky-team/husky#212]
Treat Husky as a submodule in a project, like pyhusky. It can not access Husky library in the parent's path, like HDFS.

**Comment by kygx-legend** [comment]
I have drafted a commit to set all external definitions to a variable `HUSKY_EXTERNAL_DEFINITION`. So the user is able to add this into CMakeLists.txt with `add_definitions(${HUSKY_EXTERNAL_DEFINITION})` when husky is a submodule.
