### ISSUE TITLE
Asynchronous Logging

### ISSUE THREAD

**Issue by lmatz** [husky-team/husky#219]
glog is a multi-thread synchronous logging system. Its speed may be dragged by the slow disk IO and locks. It's better to throw these blocking calls into a backend thread to deal with. Basically it's a multi-producer-single-consumer model. Thread safety may be achieved by locks or lock free queue. From the benchmark given by the author, g2log seems a efficient one built on glog and actively maintained. Or maybe we wrap the glog into an asynchronous one in our own way? what do you think?

**Comment by ddmbr** [comment]
> Its speed may be dragged by the slow disk IO and locks. 

Can you show an example or benchmark to better illustrate the impact of glog on the performance?

**Comment by kygx-legend** [comment]
Then don't log any message or reduce log functions when the performance is considered. Or use DLOG which only works on debug mode.

**Comment by lmatz** [comment]
This is an article written by the author of g2log  https://sites.google.com/site/kjellhedstrom2/g2log-efficient-background-io-processign-with-c11/g2log-vs-google-s-glog-performance-comparison              I think the main point of author is that with buffer scheme to combine multiple IO accesses into one, glog is already a fast synchronous logger. But "In the worst case scenario, when I/O wait times peak, that's when glog suffers and g2log shines".  Of course, if we don't have a massive amount of log messages to be written in real applications, the difference is not that big.

**Comment by ddmbr** [comment]
I think we may bring this issue up again if there's really a performance issue. So far I think the right thing to do is not to put too much logging in performance-critical tight loops. They hurt performance, and on the other hand, it may create too many logs which may be too over-whelming to read.
