### ISSUE TITLE
Provide iteration information to udf in multi-iterations list_execute

### ISSUE THREAD

**Issue by Yuzhen11** [husky-team/husky#22]
In multi-iterations list_execute, iteration information need to pass to user-defined functions.

Solution 1: Pass iter info as parameters to every udf. 
```c++
list_execute(list, [](Obj& obj, int iter) {
    ...
}, iters);
```

Solution 2: Use some magics to get it.
```c++
list_execute(list, [](Obj& obj) {
    auto iter = Magic::get_iter();
}, iters);
```

Solution 3: Just forbid providing iters in list_execute, force users to use for loop explicitly.
```c++
for (int iter = 0 ; iter < iters; ++iter) {
    list_execute(list, [iter](Obj& obj) { ... });
}
```

What do you think?

**Comment by kygx-legend** [comment]
The last one could have the worst performance but most user-friendly?

**Comment by ddmbr** [comment]
I'm thinking of something based on 2. In terms of implementation, I think that we can wrap `list_execute` inside a namespace, and make something like the following,

```cpp
SyncExec::batch_exec(list, [](Obj& obj) {
    auto iter = SyncExec::get_iter();
});
```

Another benefit is that we can categorize different types of `list_execute` s. In terms of non-synchronous execute, e.g., asynchronous execution, We may also get something like,

```cpp
// Inside an asynchronous execution lambda ...
auto elapsed_time = AsyncExec::get_elapsed_time();
```

**Comment by kygx-legend** [comment]
Who will take this?

**Comment by lijinf2** [comment]
I think now we can use the third one. It works for PageRank at least

**Comment by ddmbr** [comment]
Wait...

It seems that there won't be any performance issue even if we use solution 3? In this case I'll go for it. And I suggest to remove the parameter for number of iterations as well.

**Comment by Yuzhen11** [comment]
Yes, there's not performance penalty and its clear and straightforward.

**Comment by lijinf2** [comment]
I just test PageRank on LiveJournal. The performance are the same.

**Comment by ddmbr** [comment]
In this case, how about we just remove the last parameter for list_execute? It looks useless now.

**Comment by lijinf2** [comment]
It looks useless at this stage
