### ISSUE TITLE
Support inconsecutive id in AggregatorFactoryBase

### ISSUE THREAD

**Issue by lmatz** [husky-team/husky#225]
#173 supports inconsecutive id for process.
In https://github.com/husky-team/husky/blob/master/lib/aggregator.cpp#L250,  it still relies on the consecutiveness.

**Comment by Yuzhen11** [comment]
Oh yes, maybe you are right.

**Comment by zzxx-husky** [comment]
Nope. Aggregator doesn't care about whether process id is consecutive or not. Line 250 in aggregator.cpp just iterates the global worker id for all the workers. This can be replaced with `husky::WorkerInfo::get_global_tids()`

**Comment by lmatz** [comment]
I am not sure I understand it correctly. 
"factory->get_machine_id(i)" ( i from 0 to num_global_factory-1 ) eventually calls "get_process_id(i)" under WorkerInfo where a valid "global worker id" does not necessarily fall in the range of 0 to num_global_factory-1 since global worker id may be inconsecutive. Otherwise it seems that there is not need to change "global_to_proc_" from a vector to a unordered_map in #173.
And I am not sure whether "support inconsecutive id" in #173  includes "process id". If that is the case,  in line249, "fids.resize(factory->get_num_machine())" requires that "factory->get_machine_id(i)" or eventually "get_process_id(i)" should return a process id in the range of 0 to num_machines-1 which #173 doesn't not guarantee.

**Comment by zzxx-husky** [comment]
@lmatz The implementation has limitation but the aggregation itself doesn't require consecutiveness. I made a [PR](https://github.com/husky-team/husky/pull/227) to fix this.
