### ISSUE TITLE
Load data with a subset of workers

### ISSUE THREAD

**Issue by Yuzhen11** [husky-team/husky#229]
If only a subset of workers send request to master asking for block, the `files_locality_dict` cannot erase the url since the requirement `if (finished_dict[url] == num_workers_alive)` doesn't meet which means that the same url cannot be loaded twice if we don't use all the workers. 

BTW, if two subsets of the workers try to read the same url at the same time, each of the subsets cannot read the whole copy of the data.

Possible solution may be adding task id to each load task. @TatianaJin 

master/hdfs_assigner.cpp:
```c++
120     auto& files_locality = files_locality_dict[url];
121     if (files_locality.size() == 0) {
122         finish_dict[url] += 1;
123         if (finish_dict[url] == num_workers_alive)
124             files_locality_dict.erase(url);
125         return {"", 0};
126     }
```

**Comment by kygx-legend** [comment]
So @TatianaJin took this issue?

**Comment by Yuzhen11** [comment]
No, we should discuss about this first since some modifications need to be made.

**Comment by Yuzhen11** [comment]
We subclass lineinputformat and filespliter to accomplish this. See the commit 591d59c and Yuying's commit https://github.com/Yuzhen11/husky-45123/commit/30ae26a7f04e2b0636940f3b04307fe2ce0cc050.
