### ISSUE TITLE
Cannot serialize std::vector<husky::lib::Vector>?

### ISSUE THREAD

**Issue by ylchan87** [husky-team/husky#236]
Here's a aggregator that concates vector:
```
    using myT = double;
    husky::lib::Aggregator<std::vector<myT>> vecConcateAgg(
        std::vector<myT>(),
        [](std::vector<myT>& a, const std::vector<myT>& b) {
            a.insert(a.end(), b.begin(), b.end());
        },
        [](std::vector<myT>& v) { v = std::move(std::vector<myT>()); });
```

The same code, but with myT changed to husky::lib::VectorXd fails to compile
```
    using myT = husky::lib::VectorXd;
    husky::lib::Aggregator<std::vector<myT>> vecConcateAgg(
        std::vector<myT>(),
        [](std::vector<myT>& a, const std::vector<myT>& b) {
            a.insert(a.end(), b.begin(), b.end());
        },
        [](std::vector<myT>& v) { v = std::move(std::vector<myT>()); });
```
with error
```
/data/ylchan/husky/base/serialization.hpp:127:5: error: static assertion failed: For non trivially copyable type, serialization functions are needed
     static_assert(IS_TRIVIALLY_COPYABLE(OutputT),
```
However this simpler aggregator compiles:
```
husky::lib::Aggregator<husky::lib::VectorXd> vecAddAgg();
```
It seems that 
I can serialize std::vector<double>
I can serialize husky::lib::VectorXd
I cannot serialize std::vector<husky::lib::VectorXd> (unless I write my own serializer)

Is this behaviour expected? 

I made a local branch that shows the problem by modifying the aggregator.cpp example:
https://github.com/ylchan87/husky/commit/918ec819aac45b8b38bf6b3253271cda5cd1768b

**Comment by zzxx-husky** [comment]
You're right that `std::vector<husky::lib::VectorXd>` seems not to be serializable. I just checked with the following piece of code, only line 13 trigger the assertion:
```c++
#include "lib/vector.hpp"
#include "base/serialization.hpp"
using namespace husky;

int main(int argc, char** argv) {
    init_with_args(argc, argv);
    run_job([](){
        BinStream bin;
        bin << lib::VectorXd();
        bin << std::vector<int>();
        bin << std::vector<std::vector<int>>();
        bin << std::vector<std::map<int, std::vector<double>>>();
        // bin << std::vector<lib::VectorXd>();
    });
    return 0;
}
```

So far the easiest way to avoid the problem is to write your own serializer for `std::vector<husky::lib::VectorXd>`.

**Comment by zzxx-husky** [comment]
The reason `std::vector<lib::VectorXd>` finds the wrong serializer is hard to explain. But the solution seems to be putting line 78 to 120 in `lib/vector.hpp` into namespace `base`. Just a suggestion.
