### ISSUE TITLE
Some problem about the examples(PageRank)

### ISSUE THREAD

**Issue by RunyuanChen** [husky-team/husky#298]
When running the PageRank, I find there is no output file. Meanwhile, I think the format of input file should be needed.

**Comment by ddmbr** [comment]
The input format is as follows,

    <id1> <num_nbs> <nb1> <nb2> <nb3> ...
    <id2> <num_nbs> <nb1> <nb2> <nb3> ...

Everything is in integers.

As for output, could you use the [HDFS::Write()](https://github.com/husky-team/husky/blob/master/io/hdfs_manager.hpp#L56) instead? For the last argument (worker_id) you can obtain it using [Context::get_process_id()](https://github.com/husky-team/husky/blob/master/core/context.hpp#L92). Let me know if you prefer an example instead.

**Comment by RunyuanChen** [comment]
what if I want to input a weighted graph? Is there any example algorithm for weighted graph?

**Comment by Yuzhen11** [comment]
I think you can easily modify the parse function in the pagerank example. https://github.com/husky-team/husky/blob/master/examples/pagerank.cpp#L52

**Comment by RunyuanChen** [comment]
Thanks for your help!

**Comment by ph0123** [comment]
Thanks
