### ISSUE TITLE
Add an Input Format for local files to this new repo

### ISSUE THREAD

**Issue by ddmbr** [husky-team/husky#3]
Right now Husky (of this repo) only supports MongoDB and HDFS. We should migrate the support for local files to this repo as well, to ease the use on a single machine.

I'm still thinking about the name. How about we name it NFSInputFormat?

@kygx-legend Please take a look at this issue. I'll assign this to Yidi after he is added to the team.

**Comment by kygx-legend** [comment]
So does it need NFS APIs(special) to read file?

**Comment by Yuzhen11** [comment]
Yidi is in the group now, but seems that I cannot assign this issue to him. 

Maybe we should have two kinds of local inputformat, one loads from NFS another loads from each machine's local file?

**Comment by ddmbr** [comment]
@kygx-legend No need. The old code is actually designed for NFS.

**Comment by kygx-legend** [comment]
@ddmbr Just to give the path of a file only? If so, naming it with `FileInputFormat` is okay.

**Comment by ddmbr** [comment]
For reading files in local disks, there are two cases.

The first one is that the file is in NFS. In this case, we need to split the file into blocks and distribute the blocks to different readers.

The second case is that the file is not in NFS. Different parts are stored locally by different machines. Our current implementation cannot solve this case.

Actually there's a third case, but I guess it's not very useful, that is, the file is replicated in all machines. Then it can be solved in the same way as the first case.

@kygx-legend

**Comment by kygx-legend** [comment]
I see. Then do the `NFSInputFormat` first.
