### ISSUE TITLE
Error when run 'make -j4 Master'

### ISSUE THREAD

**Issue by ph0123** [husky-team/husky#306]
When I run the command, the Error 2 was appeared but I did not know what it is.
[100%] Building CXX object master/CMakeFiles/Master.dir/master_main.cpp.o
cd /usit/abel/u1/cnphuong/husky/release/master && /cluster/software/VERSIONS/gcc-7.2.0/bin/g++   -I/usit/abel/u1/cnphuong/husky -I/cluster/software/VERSIONS/boost/1.69.0/include -I/usit/abel/u1/cnphuong/.local/opt/usr/local/include -I/usit/abel/u1/cnphuong/husky/release/include -I/usit/abel/u1/cnphuong/.local/opt/eigen/eigen3  -O2 -mavx -march=sandybridge -funroll-loops -fomit-frame-pointer -Wno-deprecated-declarations -O3 -w   -std=gnu++14 -o CMakeFiles/Master.dir/master_main.cpp.o -c /usit/abel/u1/cnphuong/husky/master/master_main.cpp
make[3]: Leaving directory `/cluster/home/cnphuong/husky/release'
make[2]: *** [master/CMakeFiles/Master.dir/all] Error 2
make[2]: Leaving directory `/cluster/home/cnphuong/husky/release'
make[1]: *** [master/CMakeFiles/Master.dir/rule] Error 2
make[1]: Leaving directory `/cluster/home/cnphuong/husky/release'
make: *** [Master] Error 2

**Comment by kygx-legend** [comment]
Is it on Mac OS?

**Comment by ph0123** [comment]
On server of my university.

**Comment by ph0123** [comment]
On server at my University.

**Comment by kygx-legend** [comment]
Could you provide any other information? Besides, you can check the log of CMake/Make first.

**Comment by ph0123** [comment]
I run on Cluster server. Hence, I installed all dependence on  ~/.local/opt 
I follow installation. At the end, I run  make -j4 Master. 
I think the last line in Master is a problem.

**Comment by kygx-legend** [comment]
Based on this information, it's hard to reproduce the problem or figure out the cause. Better to check the log which shows the error of Make or try to run the compile command individually.

**Comment by ph0123** [comment]
I try to reinstall. However, It just run with 81%. Please see log file.
[logfile.txt](https://github.com/husky-team/husky/files/3112124/logfile.txt)
