### ISSUE TITLE
Run PageRank example

### ISSUE THREAD

**Issue by ph0123** [husky-team/husky#307]
I have just run './PageRank -C conf.txt --input simple_graph.txt --iters 1000 

[conf.txt](https://github.com/husky-team/husky/files/3113341/conf.txt)

I think it not work. please see the log file PageRank_husky.log
[PageRank_husky.log](https://github.com/husky-team/husky/files/3113342/PageRank_husky.log)

**Comment by kygx-legend** [comment]
please use `nfs:///path/to/file` instead

**Comment by ph0123** [comment]
Can you share dataset for pagerank?

**Comment by ph0123** [comment]
[simple_graph.txt](https://github.com/husky-team/husky/files/3131481/simple_graph.txt)

Dear all,
Can I use Husky to run this data with PageRank algorithm?
Please help me!

**Comment by kygx-legend** [comment]
Please refer to https://github.com/husky-team/husky/blob/master/examples/pagerank.cpp#L55
