### ISSUE TITLE
boost lib

### ISSUE THREAD

**Issue by ph0123** [husky-team/husky#308]
I run 
**`cmake -DCMAKE_BUILD_TYPE=Release \
	-DBOOST_ROOT=/cluster/software/VERSIONS/boost/1.69.0 \
    -DEIGEN_INCLUDE_DIR=$HOME/.local/opt/eigen \
    -DCMAKE_PREFIX_PATH=$HOME/.local/opt/usr/local/ \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    .. 
`**
the error was appeared when I run  **### `make VERBOSE=1 -j4 Master`**
`log.cpp:(.text+0x52a): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
log.cpp:(.text+0x542): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
log.cpp:(.text+0x588): undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
`
I used `load module boost/1.69.0` from the cluster server. 

Could you tell me how to solve this problem?

**Comment by aminmkhan** [comment]
Since you have compiled `boost` module from source, can you check if any other version of `boost` is not already present or loaded in the cluster?

```bash
module list
module unload boost
```

**Comment by kygx-legend** [comment]
`CMAKE_PREFIX_PATH` does not include your boost? Then you may check `LD_LIBRARY_PATH`. Looks like `module load` could add the env?
