### ISSUE TITLE
FileInputFormat

### ISSUE THREAD

**Issue by zzxx-husky** [husky-team/husky#48]
To create HDFSFileInputFormat and NFSFileInputFormat to support reading binary files from HDFS and NFS. The basic processing unit will a file. Instead of using `std::string` or `boost::string_ref` as record type, here a stream is given for reading from one file.

Need to design a new class to represent a file as a stream. This class may extend existing `BinStream`(?) and overrides the `pop_front_back` function. And the parse lambda used in `load()` must use reference for catching this stream. The `load()` function may need to be modified, because we're not going to create a BinStream object in the `load()` function. Instread an object of a subclass of BinStream is created. But what's passed to the users is a BinStream object.

Modification may be
```c++
typename InputFormatT::RecordT record;  // subclass type here, or even pointer type here
bool success = false;
while (true) {
    success = infmt.next(record);
    if (success == false)
        break;
    // parse(record);
    parse(InputFormatT::recast(record));  // change the type from subclass to base class
}
```
And a default recast function needs to be added in `InputFormatBase`
```c++
template<typename T>
static T& recast(T& t) {
  return t;
}
```

**Comment by zzxx-husky** [comment]
Cannot assign it to me ...

**Comment by kygx-legend** [comment]
done.

**Comment by ddmbr** [comment]
If I understand it correctly, you will need many files for this InputFormat to make sense, right? Because in this case, file is the smallest unit.

**Comment by kygx-legend** [comment]
Provide a list of files or a path of directory?

**Comment by lijinf2** [comment]
I remember that Yuzhen developed chunkinputformat before. We can define the number of bytes for each record. The chunkinputformat can read binary files from HDFS in a way similar to text files, and the interfaces are quite nice. Do you need the same input format or others ?

**Comment by zzxx-husky** [comment]
@ddmbr @kygx-legend Yes, that needs a lot of files to make sense. Here I am thinking a user can provide a path to a file or a directory, and also a regex-based filter.

@lijinf2 As I can remember, the size of the chunk of the chunkinputformat needs to be fixed. But in common cases, the lengths of records are different. It's a normal case that I read the length of the record first and then I read the record itself.
