### ISSUE TITLE
An access_next method in ShuffleCombiner

### ISSUE THREAD

**Issue by ddmbr** [husky-team/husky#49]
In the past the shuffle combine logic looks complicated and it's scattered in many places, but now it looks much organized. In terms of performance, however, there's definitely room for improvement.

Now the logic is that we access the buffers one by one. Before accessing a buffer, we need to make sure it's available and this results in waiting. However we don't care about the order. We actually can access any buffer once it becomes available. The access_next method means accessing the next available buffer.

The ShuffleCombiner code looks straightforward to me. However, starting from Accessor it becomes harder to me. I think a straightforward approach is we do some message passing. Once a buffer is available, a message will be sent from the Shuffler to the ShuffleCombiner. In this case, the ShuffleCombiner has knowledge about what buffers are available and what buffers are not at any time.

Any idea?

**Comment by zzxx-husky** [comment]
It seems a no-lock concurrent queue (may find one in boost) is situable for you.

**Comment by ddmbr** [comment]
spsc_queue? But in this case there are more than one producer per queue.

**Comment by xwkuang5** [comment]
I just used **19** machines(worker1-worker19) with **2** threads on each to run the `BenchPageRank` on `/datasets/graph/twitters` for **10** iterations. On average each iteration of **ZeroMQ ShuffleCombiner** takes **60.9s** and the old **ShuffleCombiner** takes **63.8s**. @ddmbr.

**Comment by ddmbr** [comment]
Hi @xwkuang5 , Can you try to use 20 threads instead?

**Comment by xwkuang5** [comment]
I ran the `BenchPageRank` for another three times. Each time the `ZeroMQ ShuffleCombiner` version is run first, then the `old ShuffleCombiner` version. Using 19 machines with 20 threads each and iter = 10,  `ZeroMQ ShuffleCombiner` on average takes 9.82 seconds per iteration and `oldShuffleCombiner` on average takes 10.82 seconds per iteration. Should I use more iterations? @ddmbr

**Comment by ddmbr** [comment]
Hi @xwkuang5 . I suspect that you are not using release mode?

**Comment by xwkuang5** [comment]
Yes, I'm using debug mode.

**Comment by ddmbr** [comment]
You should always use release mode when you are doing benchmarks

**Comment by xwkuang5** [comment]
Okay, what else should I try?

**Comment by ddmbr** [comment]
The twitter numbers with release mode should suffice.

**Comment by xwkuang5** [comment]
Here are the numbers from running 19 machines(1-3,5-20) with 20 threads on each machine in release mode for 10 iterations:
`ZeroMQ ShuffleCombiner`: On average, Iteration 1 takes 15.67 seconds, Iteration 0 and other Iterations takes 3.21 seconds.
`Accessor ShuffleCombiner`: On average, Iteration 1 takes 13.62 seconds, Iteration 0 and other Iterations takes 3.52 seconds.

It seems that` ZeroMQ ShuffleCombiner `can be several seconds slower than the `Accessor ShuffleCombiner `in Iteration 1(getting from channel for the first time).

**Comment by ddmbr** [comment]
Looks good to me. I'll merge your PR and close this issue. However, you need to think about how to remove the overhead of the first iteration.

**Comment by xwkuang5** [comment]
I need to fix some formatting issues first.
