### ISSUE TITLE
The possibility of inlining functions in Context

### ISSUE THREAD

**Issue by Yuzhen11** [husky-team/husky#67]
Separating the definition and declaration of the functions in Context may disable the opportunity of inlining these functions such as get_local_id(), get_param(), etc. 

The reason is that most build environments do inlining during compilation. I think for functions that need to be inline, it'd better to put the definition and declaration together.

**Comment by kygx-legend** [comment]
To make all `get` functions inline is enough.

**Comment by ddmbr** [comment]
I think we should do this based on profiling result. Functions that are called inside a tight loop should be inlined.

**Comment by kygx-legend** [comment]
Write a small test?
