### ISSUE TITLE
Travis CI fails in HuskyUnitTest sometimes

### ISSUE THREAD

**Issue by kygx-legend** [husky-team/husky#96]

**Comment by kygx-legend** [comment]
The same: TestMailbox.SendRecvOnceAsync

**Comment by kygx-legend** [comment]
Interesting: HuskyUnitTest encounters segmentation fault in case TestGenerationLock.GenerationLock on my desktop.

**Comment by ddmbr** [comment]
I'll take this

**Comment by ddmbr** [comment]
How about we close it for now, and reopen it if the problem persists? Or we may open a better one targeting at a specific component.

**Comment by kygx-legend** [comment]
I think it doesn't matter. This issue can be kept to record the failures of unit test and then we can track directly.

**Comment by ddmbr** [comment]
TestPushCombinedChannel.IncProgress failed: https://travis-ci.org/husky-team/husky/builds/172012232

**Comment by kygx-legend** [comment]
TestPushCombinedChannel.IncProgress failed for timeout sometimes. Not sure if this is caused by the case itself.

**Comment by kygx-legend** [comment]
Still need to find a way to reproduce.

**Comment by kygx-legend** [comment]
It seems this does not occur frequently so I close this.
